sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

# you can specify futher versions as found at http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.7"
  - development
  
matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install travix
  # to always use the latest version of travix comment out the previous line and uncomment the next
  # - haxelib git travix https://github.com/back2dos/travix && pushd . && cd $(haxelib config)travix/git && haxe build-neko.hxml && popd
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  - haxelib run travix js
  # - haxelib run travix flash
  - haxelib run travix java
  - haxelib run travix cpp
  - haxelib run travix cs
  # - haxelib run travix php
  - haxelib run travix php7
  - haxelib run travix lua
